cmake_minimum_required(VERSION 3.28)

include(FetchContent)

FetchContent_Declare(
    googletest
    URL https://github.com/google/googletest/archive/refs/tags/v1.17.0.zip
    DOWNLOAD_EXTRACT_TIMESTAMP TRUE
)

FetchContent_MakeAvailable(googletest)

include(GoogleTest)

function(add_tensor_test TARGET_NAME SOURCE_FILE)

    add_executable(${TARGET_NAME}
        ${SOURCE_FILE}
    )

    target_link_libraries(${TARGET_NAME}
        PRIVATE
            Tensor
            GTest::gtest_main
    )

    gtest_discover_tests(${TARGET_NAME})

endfunction()

# ----------------- Tensor Tests -----------------
add_tensor_test(test_tensor_properties tensor/test_tensor_properties.cpp)
add_tensor_test(test_tensor_arithmetic tensor/test_tensor_arithmetic.cpp)
add_tensor_test(test_tensor_matmul tensor/test_tensor_matmul.cpp)
add_tensor_test(test_tensor_broadcast tensor/test_tensor_broadcast.cpp)
add_tensor_test(test_tensor_reduction tensor/test_tensor_reduction.cpp)
add_tensor_test(test_tensor_shapeOps tensor/test_tensor_shapeOps.cpp)

# ----------------- Layers Tests -----------------
add_tensor_test(test_layer_linear layer/test_linear.cpp)
add_tensor_test(test_layer_dropout layer/test_dropout.cpp)
add_tensor_test(test_layer_sequential layer/test_sequential.cpp)